project:
  type: website
  output-dir: docs
  resources:
    - files/**

website:
  title: "keisuke-hanada"
  google-analytics: "G-80RE24GCEC"
  body-footer: Copyright by Keisuke Hanada
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: background.qmd
      - href: research.qmd
      - href: tools.qmd
      - href: teaching.qmd
      - href: column/index.qmd
    right:
      - icon: rss
        href: column/index.xml
  site-url: https://keisuke-hanada.github.io
  site-path: '/'


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

